#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 23, 2020 09:28:01 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Cuckoo_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Cuckoo_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Cuckoo_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("816x724+434+150")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(relx=0.27, rely=0.014, height=24, width=326)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(justify='center')
        self.TLabel1.configure(text='''Steganography using Cuckoo Search Algorithm''')
        self.TLabel1.configure(width=326)

        self.TLabel2 = ttk.Label(top)
        self.TLabel2.place(relx=0.049, rely=0.083, height=24, width=134)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief="flat")
        self.TLabel2.configure(text='''Choose cover imge:''')

        self.TLabel3 = ttk.Label(top)
        self.TLabel3.place(relx=0.049, rely=0.124, height=24, width=145)
        self.TLabel3.configure(background="#d9d9d9")
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(font="TkDefaultFont")
        self.TLabel3.configure(relief="flat")
        self.TLabel3.configure(text='''Choose secret image:''')

        self.TLabel4 = ttk.Label(top)
        self.TLabel4.place(relx=0.049, rely=0.207, height=24, width=62)
        self.TLabel4.configure(background="#d9d9d9")
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(font="TkDefaultFont")
        self.TLabel4.configure(relief="flat")
        self.TLabel4.configure(text='''OUTPUT:''')

        self.TLabel5 = ttk.Label(top)
        self.TLabel5.place(relx=0.049, rely=0.276, height=24, width=50)
        self.TLabel5.configure(background="#d9d9d9")
        self.TLabel5.configure(foreground="#000000")
        self.TLabel5.configure(font="TkDefaultFont")
        self.TLabel5.configure(relief="flat")
        self.TLabel5.configure(text='''COVER''')

        self.TLabel6 = ttk.Label(top)
        self.TLabel6.place(relx=0.576, rely=0.276, height=24, width=54)
        self.TLabel6.configure(background="#d9d9d9")
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(font="TkDefaultFont")
        self.TLabel6.configure(relief="flat")
        self.TLabel6.configure(text='''SECRET''')

        self.TLabel7 = ttk.Label(top)
        self.TLabel7.place(relx=0.061, rely=0.525, height=24, width=65)
        self.TLabel7.configure(background="#d9d9d9")
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(font="TkDefaultFont")
        self.TLabel7.configure(relief="flat")
        self.TLabel7.configure(text='''STEGO''')
        self.TLabel7.configure(width=65)

        self.Custom1 = Cuckoo_support.Custom(top)
        self.Custom1.place(relx=0.147, rely=0.58, relheight=0.088
                , relwidth=0.103)

        self.TLabe = ttk.Label(top)
        self.TLabe.place(relx=0.588, rely=0.525, height=24, width=128)
        self.TLabe.configure(background="#d9d9d9")
        self.TLabe.configure(foreground="#000000")
        self.TLabe.configure(font="TkDefaultFont")
        self.TLabe.configure(relief="flat")
        self.TLabe.configure(text='''REVEALED SECRET''')

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.098, rely=0.359, height=30, width=98)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Tbutton''')

        self.TButton2 = ttk.Button(top)
        self.TButton2.place(relx=0.625, rely=0.373, height=30, width=98)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Tbutton''')

        self.TButton3 = ttk.Button(top)
        self.TButton3.place(relx=0.123, rely=0.691, height=30, width=98)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Tbutton''')

        self.TButton4 = ttk.Button(top)
        self.TButton4.place(relx=0.637, rely=0.691, height=30, width=98)
        self.TButton4.configure(takefocus="")
        self.TButton4.configure(text='''Tbutton''')

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.147, rely=0.925, relheight=0.061, relwidth=0.311)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=254)
        self.Text1.configure(wrap="word")

        self.Text2 = tk.Text(top)
        self.Text2.place(relx=0.662, rely=0.925, relheight=0.061, relwidth=0.287)

        self.Text2.configure(background="white")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(width=234)
        self.Text2.configure(wrap="word")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.049, rely=0.939, height=26, width=35)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''MSE''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.564, rely=0.939, height=26, width=42)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''PSNR''')

if __name__ == '__main__':
    vp_start_gui()





